// Generated by CoffeeScript 1.4.0
// See FMRMaker_List.coffee in FMR Maker 3mm.app/Contents/BV Scripts for commented code
  
  // -------- PASTE TEXT FILE PATH BETWEEN QUOTES -------- 
  filename = String("PASTE PATH HERE");

var filename, projfls, readTextFile;

readTextFile = function(name) {
  var docFMR, filenamesfile, i, no_slices, no_volumes, nroffiles, resolution, rows, save_fileName, save_path, source_file, textstr;
  BrainVoyagerQX.PrintToLog("Reading: " + name);
  filenamesfile = new QFile(name);
  filenamesfile.open(new QIODevice.OpenMode(QIODevice.ReadOnly));
  textstr = new QTextStream(filenamesfile);
  nroffiles = parseInt(textstr.readLine());
  no_slices = parseInt(textstr.readLine());
  rows = parseInt(textstr.readLine());
  resolution = parseInt(textstr.readLine());
  i = 0;
  while (i < nroffiles) {
    source_file = textstr.readLine();
    no_volumes = textstr.readLine();
    name = textstr.readLine();
    save_path = textstr.readLine();
    save_fileName = textstr.readLine();
    docFMR = BrainVoyagerQX.CreateProjectMosaicFMR("DICOM", source_file, no_volumes, 0, false, no_slices, name, false, rows, rows, 2, save_path, 1, resolution, resolution);
    docFMR.SaveAs(save_fileName);
    docFMR.Close();
    i++;
  }
  return filenamesfile.close();
};

projfls = this.readTextFile(filename);
